
IMM_FILES=IMM_active_zones_1 \
IMM_add_casts_spell_1 \
IMM_add_keyword_1 \
IMM_add_kname_1 \
IMM_add_mname_1 \
IMM_add_mob_script_1 \
IMM_add_oname_1 \
IMM_add_path_1 \
IMM_add_perm_inv_1 \
IMM_add_proc_1 \
IMM_add_rem_names_1 \
IMM_add_stat_affect_1 \
IMM_adlist_1 \
IMM_adsave_1 \
IMM_amlist_1 \
IMM_amsave_1 \
IMM_aolist_1 \
IMM_aosave_1 \
IMM_arlist_1 \
IMM_ch_ddesc_1 \
IMM_ch_kdesc_1 \
IMM_ch_mdesc_1 \
IMM_ch_mndesc_1 \
IMM_ch_msdesc_1 \
IMM_ch_odesc_1 \
IMM_ch_ondesc_1 \
IMM_ch_osdesc_1 \
IMM_ch_path_desc_1 \
IMM_ch_rdesc_1 \
IMM_ch_rname_1 \
IMM_ch_zname_1 \
IMM_classes_1 \
IMM_clear_keyword_1 \
IMM_create_conct_1 \
IMM_create_constrct_1 \
IMM_dclear_1 \
IMM_delete_door_1 \
IMM_dlist_1 \
IMM_door_to_1 \
IMM_dset_1 \
IMM_dstat_1 \
IMM_dsys_1 \
IMM_dvnum_1 \
IMM_enslave_1 \
IMM_flip_door_1 \
IMM_force_1 \
IMM_force_all_1 \
IMM_freeze_1 \
IMM_gag_1 \
IMM_gecho_1 \
IMM_goto_1 \
IMM_itrans_1 \
IMM_keyword_1 \
IMM_ldwho_1 \
IMM_list_paths_1 \
IMM_list_scripts_1 \
IMM_list_site_bans_1 \
IMM_log_level_1 \
IMM_make_builder_1 \
IMM_make_pso_1 \
IMM_mclear_1 \
IMM_mclone_1 \
IMM_mlist_1 \
IMM_mload_1 \
IMM_mreload_1 \
IMM_mset_1 \
IMM_mstat_1 \
IMM_mvnum_1 \
IMM_oclear_1 \
IMM_oclone_1 \
IMM_olc_1 \
IMM_olist_1 \
IMM_oload_1 \
IMM_opurge_1 \
IMM_oreload_1 \
IMM_oset_1 \
IMM_ostat_1 \
IMM_ovnum_1 \
IMM_poofin_1 \
IMM_possess_1 \
IMM_rclear_1 \
IMM_rclone_1 \
IMM_rem_mname_1 \
IMM_rem_oname_1 \
IMM_rem_path_1 \
IMM_rem_perm_inv_1 \
IMM_replace_door_1 \
IMM_reset_olc_1 \
IMM_rezone_1 \
IMM_rinit_1 \
IMM_rlist_1 \
IMM_rm_bow_proc_1 \
IMM_rm_casts_spell_1 \
IMM_rm_curse_proc_1 \
IMM_rm_discuss_proc_1 \
IMM_rm_give_proc_1 \
IMM_rm_keyword_1 \
IMM_rm_script_1 \
IMM_rm_stat_affect_1 \
IMM_rset_1 \
IMM_rstat_1 \
IMM_save_mob_1 \
IMM_save_obj_1 \
IMM_see_all_1 \
IMM_set_path_dir_1 \
IMM_set_path_pointer_1 \
IMM_set_veh_stop_1 \
IMM_shutdown_1 \
IMM_siteban_1 \
IMM_slay_1 \
IMM_slist_1 \
IMM_smob_1 \
IMM_snoop_1 \
IMM_sockets_1 \
IMM_stat_keyword_1 \
IMM_stat_path_1 \
IMM_stat_script_1 \
IMM_teach_1 \
IMM_thaw_1 \
IMM_tog_mflag_1 \
IMM_tog_oflag_1 \
IMM_tog_rflag_1 \
IMM_tog_veh_stop_1 \
IMM_tog_zflag_1 \
IMM_total_rezone_1 \
IMM_ungag_1 \
IMM_unpossess_1 \
IMM_unpost_1 \
IMM_unsiteban_1 \
IMM_unsnoop_1 \
IMM_update_CIG_1 \
IMM_update_cig_1 \
IMM_uptime_1 \
IMM_visible_1 \
IMM_wizinvis_1 \
IMM_write_world_1 \
IMM_write_zone_1 \
IMM_zcreate_1 \
IMM_zdisable_1 \
IMM_zenable_1 \
IMM_zgoto_1 \
IMM_zlist_1 \
IMM_zlock_1 \
IMM_zunlock_1



MORT_FILES=abilities_1 \
adjust_register_1 \
anitre_1 \
assist_1 \
backstab_1 \
bash_1 \
beep_1 \
berserk_1 \
bodyslam_1 \
brief_1 \
bug_1 \
butcher_1 \
buy_1 \
cast_1 \
channels_1 \
circle_1 \
claw_1 \
close_1 \
color_1 \
commands_1 \
concoct_1 \
consider_1 \
construct_1 \
credits_1 \
curse_1 \
darkling_1 \
date_1 \
disarm_1 \
discuss_1 \
donate_1 \
down_1 \
drink_1 \
drop_1 \
dwarf_1 \
east_1 \
eat_1 \
elf_1 \
emote_1 \
empty_1 \
eq_1 \
examine_1 \
exit_1 \
exits_1 \
fill_1 \
flee_1 \
follow_1 \
get_1 \
give_1 \
go_1 \
group_1 \
guard_1 \
help_1 \
hit_1 \
hold_1 \
human_1 \
hurl_1 \
idea_1 \
inventory_1 \
ironclad_1 \
junk_1 \
list_1 \
lock_1 \
look_1 \
meditate_1 \
move_1 \
nogossip_1 \
north_1 \
northeast_1 \
northwest_1 \
offer_1 \
ogrue_1 \
open_1 \
order_1 \
page_break_1 \
passwd_1 \
pay_1 \
picklock_1 \
post_1 \
practice_1 \
prompt_1 \
prone_1 \
put_1 \
quaf_1 \
quit_1 \
races_1 \
read_1 \
recite_1 \
regeneration_1 \
remove_1 \
reply_1 \
rest_1 \
roll_1 \
save_1 \
say_1 \
scan_1 \
score_1 \
scribe_1 \
sell_1 \
shield_1 \
shoot_1 \
shout_1 \
sit_1 \
skin_1 \
sleep_1 \
sneak_1 \
socials_1 \
sombre_1 \
south_1 \
southeast_1 \
southwest_1 \
stand_1 \
suicide_1 \
tail_1 \
tell_1 \
theme_1 \
throw_1 \
time_1 \
title_1 \
toggle_1 \
track_1 \
ungroup_1 \
unlock_1 \
up_1 \
use_1 \
value_add_1 \
value_list_1 \
value_rem_1 \
value_set_1 \
wake_1 \
wear_1 \
west_1 \
where_1 \
who_1 \
wield_1 \
wimpy_1 \
wizlist_1



all: imm_idx mort_idx
	../help_filter/help2html imm_help.html IMM*_[1-9]
	../help_filter/help2html mort_help.html [a-z]*_[1-9]

imm_idx: IMM_wizhelp_1

IMM_wizhelp_1: ${IMM_FILES}
	rm -f IMM_wizhelp_1
	@echo "<help immortal wizhelp>" > IMM_wizhelp_1
	@echo "" >> IMM_wizhelp_1
	@echo "Here is a list of all immortal/builder help topics." >> IMM_wizhelp_1
	@echo "" >> IMM_wizhelp_1
	../help_filter/idx_bldr IMM*_[1-9] >> IMM_wizhelp_1
	@echo "" >> IMM_wizhelp_1
	@echo "<color=red>" >> IMM_wizhelp_1
	@echo "See Also:  commands, topics" >> IMM_wizhelp_1
	@echo "</color></help>" >> IMM_wizhelp_1


mort_idx: topics_1

topics_1: ${MORT_FILES}
	rm -f topics_1
	@echo "<help general topics>" > topics_1
	@echo "" >> topics_1
	@echo "Here is a list of all mortal help topics." >> topics_1
	@echo "" >> topics_1
	../help_filter/idx_bldr [a-z]*_[1-9] >> topics_1
	@echo "" >> topics_1
	@echo "<color=red>" >> topics_1
	@echo "See Also:  commands, wizhelp" >> topics_1
	@echo "</color></help>" >> topics_1

clean:
	rm -f imm_help.html
	rm -f mort_help.html

purge: clean
	rm -f IMM_wizhelp_1
	rm -f topics_1