# $Id$
# $Revision: 1.2 $  $Author$ $Date$

include ../MakeInclude

all:
	${MAKE} -C log all
	${MAKE} -C string2 all
	${MAKE} -C containers all
	${MAKE} -C bitfield all

clean:
	${MAKE} -C containers clean
	${MAKE} -C bitfield clean
	${MAKE} -C log clean
	${MAKE} -C string2 clean



