#!/bin/sh

LOG_FILE=$1

if [ $# = "0" ]
then
   echo "Called as: $*"
   echo "Usage:  %0 <file_name>"
   exit 2
fi

if [ -f ${LOG_FILE} ]
then

    grep ERROR ${LOG_FILE} > /tmp/ERROR.lg
    if [ $? = 0 ]; then
	echo "" >> ./log/ERROR.lg
	echo -n "***************  " >> ./log/ERROR.lg
	date >> log/ERROR.lg
	cat /tmp/ERROR.lg >> ./log/ERROR.lg
    fi

    grep WARN ${LOG_FILE} > /tmp/WARN.lg
    if [ $? = 0 ]; then
	echo "" >> ./log/WARN.lg
	echo -n "******************  " >> ./log/WARN.lg
	date >> ./log/WARN.lg
	cat /tmp/WARN.lg >> ./log/WARN.lg
    fi

    exit 0

else

   echo "File not found: ${LOG_FILE}"
   echo "Called as: $*"
   echo "Usage:  $0 <file_name>"

   exit 1
fi
