#!/bin/sh

LOG_FILE=$1

#echo -n "In truncate_log.."

if [ $# = "0" ]
then
   echo "Called as: $*"
   echo "Usage:  %0 <file_name>"
   exit 2
fi

if [ -f ${LOG_FILE} ]
then

    grep ERROR ${LOG_FILE} > /tmp/ERROR.lg
    if [ $? = 0 ]; then
	echo "" >> ./log/ERROR.lg
	echo -n "***************  " >> ./log/ERROR.lg
	date >> log/ERROR.lg
	cat /tmp/ERROR.lg >> ./log/ERROR.lg
	tail -3000 ./log/ERROR.lg > /tmp/ERROR.lg.tmp
	mv /tmp/ERROR.lg.tmp ./log/ERROR.lg
    fi

    grep WARN ${LOG_FILE} > /tmp/WARN.lg
    if [ $? = 0 ]; then
	echo "" >> ./log/WARN.lg
	echo -n "******************  " >> ./log/WARN.lg
	date >> ./log/WARN.lg
	cat /tmp/WARN.lg >> ./log/WARN.lg
	tail -3000 ./log/WARN.lg > /tmp/ERROR.lg.tmp
	mv /tmp/ERROR.lg.tmp ./log/WARN.lg
    fi

    #  Get rid of crash files if there are too many
    ls -t ./log/logfile*CRASH* | xargs crash_sanity
    ls -t ./log/obj_ptr*CRASH* | xargs crash_sanity

    exit 0

else

   echo "File not found: ${LOG_FILE}"
   echo "Called as: $*"
   echo "Usage:  $0 <file_name>"

   exit 1
fi

echo "...  Done with truncate log."